// ui/src/app/(auth)/init/page.tsx
"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthActions, useAuthIsLoading } from '@/stores/auth';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ClosableAlert } from "@/components/ui/closable-alert";
import { Settings, User, Lock, Info } from 'lucide-react';

export default function InitPage() {
  const router = useRouter();
  const { init, checkInit } = useAuthActions();
  const isLoading = useAuthIsLoading();

  const [form, setForm] = useState({ username: '', password: '', confirmPassword: '' });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  useEffect(() => {
    const initialize = async () => {
      const initialized = await checkInit();
      if (initialized) {
        router.push('/login');
      }
    };
    initialize();
  }, [checkInit, router]);

  const handleInit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    if (form.password !== form.confirmPassword) {
      setError('密码不匹配');
      return;
    }
    if (form.password.length < 6) {
      setError('密码长度至少为6位');
      return;
    }

    const result = await init({ username: form.username, password: form.password });
    if (result.success) {
      setSuccess(result.message);
      setTimeout(() => router.push('/'), 1500);
    } else {
      setError(result.message);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-green-50 to-emerald-100">
      <div className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-md">
          <div className="text-center mb-8">
            <div className="mx-auto w-16 h-16 bg-green-600 rounded-full flex items-center justify-center mb-4">
              <Settings className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              系统初始化
            </h1>
            <p className="text-gray-600">
              首次使用，请设置管理员账户
            </p>
          </div>

          <Card className="shadow-xl">
            <CardHeader>
              <CardTitle>创建管理员</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleInit} className="space-y-6">
                {error && <ClosableAlert variant="destructive" title="错误" onClose={() => setError('')}>{error}</ClosableAlert>}
                {success && <ClosableAlert title="成功" onClose={() => setSuccess('')}>{success}</ClosableAlert>}

                <div className="space-y-2">
                  <Label htmlFor="username">管理员用户名</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="username"
                      name="username"
                      value={form.username}
                      onChange={handleChange}
                      placeholder="输入管理员用户名"
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">密码</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="password"
                      name="password"
                      type="password"
                      value={form.password}
                      onChange={handleChange}
                      placeholder="输入密码 (至少6位)"
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">确认密码</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="confirmPassword"
                      name="confirmPassword"
                      type="password"
                      value={form.confirmPassword}
                      onChange={handleChange}
                      placeholder="再次输入密码"
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <Button type="submit" disabled={isLoading} className="w-full mt-8" variant="default">
                  {isLoading ? '初始化中...' : '完成初始化'}
                </Button>
              </form>
            </CardContent>
          </Card>

          <div className="text-center mt-6">
            <div className="flex items-center justify-center space-x-2 text-sm text-gray-500">
                <Info className="w-4 h-4" />
                <span>此操作只需执行一次，用于创建第一个管理员帐户。</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// web/pages/init.vue
<template>
  <div class="min-h-screen flex flex-col bg-gray-50">
    <div class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full space-y-8">
        <div>
          <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
            系统初始化
          </h2>
          <p class="mt-2 text-center text-sm text-gray-600">
            首次使用，请设置管理员账户
          </p>
        </div>
        
        <form class="mt-8 space-y-6" @submit.prevent="handleInit">
          <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
            {{ error }}
          </div>
          
          <div v-if="success" class="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded">
            {{ success }}
          </div>
          
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <label for="username" class="sr-only">用户名</label>
              <input
                id="username"
                v-model="form.username"
                name="username"
                type="text"
                required
                class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="管理员用户名"
              />
            </div>
            <div>
              <label for="password" class="sr-only">密码</label>
              <input
                id="password"
                v-model="form.password"
                name="password"
                type="password"
                required
                minlength="6"
                class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="密码 (至少6位)"
              />
            </div>
            <div>
              <label for="confirmPassword" class="sr-only">确认密码</label>
              <input
                id="confirmPassword"
                v-model="form.confirmPassword"
                name="confirmPassword"
                type="password"
                required
                class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="确认密码"
              />
            </div>
          </div>

          <div>
            <button
              type="submit"
              :disabled="authStore.isLoading"
              class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:opacity-50"
            >
              {{ authStore.isLoading ? '初始化中...' : '初始化系统' }}
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- 初始化页面底部商标信息 -->
    <AppFooter 
      :show-privacy-policy="false"
      :show-terms-of-service="false"
      page-info="系统初始化向导"
    />
  </div>
</template>

<script setup>
import { useAuthStore } from '~/stores/auth'

definePageMeta({
  layout: false
})

const authStore = useAuthStore()

const form = reactive({
  username: '',
  password: '',
  confirmPassword: ''
})

const error = ref('')
const success = ref('')

onMounted(async () => {
  // 检查是否已初始化
  const initialized = await authStore.checkInit()
  if (initialized) {
    await navigateTo('/login')
  }
})

const handleInit = async () => {
  error.value = ''
  success.value = ''
  
  // 验证密码
  if (form.password !== form.confirmPassword) {
    error.value = '两次输入的密码不一致'
    return
  }
  
  if (form.password.length < 6) {
    error.value = '密码至少需要6位'
    return
  }
  
  const result = await authStore.init({
    username: form.username,
    password: form.password
  })
  
  if (result.success) {
    success.value = result.message
    setTimeout(() => {
      navigateTo('/')
    }, 1500)
  } else {
    error.value = result.message
  }
}
</script>
