// ui/src/app/(auth)/login/page.tsx
"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthActions, useAuthIsLoading, useIsAuthenticated } from '@/stores/auth';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Server, User, Lock, LogIn, AlertCircle } from 'lucide-react';

export default function LoginPage() {
  const router = useRouter();
  const { login, checkInit } = useAuthActions();
  const isAuthenticated = useIsAuthenticated();
  const isLoading = useAuthIsLoading();

  const [form, setForm] = useState({ username: '', password: '' });
  const [error, setError] = useState('');

  useEffect(() => {
    const initialize = async () => {
      const initialized = await checkInit();
      if (!initialized) {
        router.push('/init');
      } else if (isAuthenticated) {
        router.push('/');
      }
    };
    initialize();
  }, [checkInit, isAuthenticated, router]);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    const result = await login(form);
    if (result.success) {
      router.push('/');
    } else {
      setError(result.message);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-md">
          <div className="text-center mb-8">
            <div className="mx-auto w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center mb-4">
              <Server className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              登录到您的账户
            </h1>
            <p className="text-gray-600">
              管理您的 ARK 服务器
            </p>
          </div>

          <Card className="shadow-xl">
            <CardHeader>
              <CardTitle>登录</CardTitle>
              <CardDescription>请输入您的凭据以继续</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleLogin} className="space-y-6">
                {error && (
                  <Alert variant="destructive">
                    <AlertCircle className="h-4 w-4" />
                    <AlertTitle>错误</AlertTitle>
                    <AlertDescription>{error}</AlertDescription>
                  </Alert>
                )}
                <div className="space-y-2">
                  <Label htmlFor="username">用户名</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="username"
                      name="username"
                      value={form.username}
                      onChange={handleChange}
                      placeholder="输入您的用户名"
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">密码</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="password"
                      name="password"
                      type="password"
                      value={form.password}
                      onChange={handleChange}
                      placeholder="输入您的密码"
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <Button type="submit" disabled={isLoading} className="w-full mt-8">
                  {isLoading ? (
                    '登录中...'
                  ) : (
                    <>
                      <LogIn className="w-4 h-4 mr-2" />
                      登录
                    </>
                  )}
                </Button>
              </form>
            </CardContent>
          </Card>

          <div className="text-center mt-6">
            <p className="text-sm text-gray-500">
              首次使用？系统将使用您在此处输入的凭据创建管理员帐户。
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// ui/app/pages/login.vue
<template>
  <div class="min-h-screen flex flex-col bg-gradient-to-br from-blue-50 to-indigo-100">
    <div class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="w-full max-w-md">
        <!-- Logo 和标题区域 -->
        <div class="text-center mb-8">
          <div class="mx-auto w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center mb-4">
            <UIcon name="i-lucide-server" class="w-8 h-8 text-white" />
          </div>
          <h1 class="text-3xl font-bold text-gray-900 mb-2">
            ARK 服务器管理器
          </h1>
          <p class="text-gray-600">
            安全登录您的管理账户
          </p>
        </div>
        
        <!-- 登录表单卡片 -->
        <UCard class="shadow-xl">
          <form @submit.prevent="handleLogin" class="space-y-6">
            <!-- 错误提示 -->
            <UAlert
              v-if="error"
              :title="error"
              color="red"
              variant="soft"
              icon="i-lucide-alert-circle"
            />
            
            <!-- 用户名输入 -->
            <UFormGroup label="用户名" name="username">
              <UInput
                v-model="form.username"
                placeholder="请输入用户名"
                icon="i-lucide-user"
                size="lg"
                required
              />
            </UFormGroup>
            
            <!-- 密码输入 -->
            <UFormGroup label="密码" name="password">
              <UInput
                v-model="form.password"
                type="password"
                placeholder="请输入密码"
                icon="i-lucide-lock"
                size="lg"
                required
              />
            </UFormGroup>

            <!-- 登录按钮 -->
            <UButton
              type="submit"
              :loading="authStore.isLoading"
              :disabled="authStore.isLoading"
              color="blue"
              variant="solid"
              size="lg"
              block
              class="mt-8"
            >
              <UIcon 
                v-if="!authStore.isLoading" 
                name="i-lucide-log-in" 
                class="w-4 h-4 mr-2" 
              />
              {{ authStore.isLoading ? '登录中...' : '登录' }}
            </UButton>
          </form>
        </UCard>
        
        <!-- 底部提示 -->
        <div class="text-center mt-6">
          <p class="text-sm text-gray-500">
            首次使用？系统将自动引导您完成初始化
          </p>
        </div>
      </div>
    </div>

    <!-- 登录页面底部商标信息 -->
    <AppFooter 
      :show-privacy-policy="false"
      :show-terms-of-service="false"
      page-info="安全登录系统"
    />
  </div>
</template>

<script setup>
import { useAuthStore } from '~/stores/auth'

definePageMeta({
  layout: false
})

const authStore = useAuthStore()
const router = useRouter()

const form = reactive({
  username: '',
  password: ''
})

const error = ref('')

onMounted(async () => {
  // 检查是否已初始化
  const initialized = await authStore.checkInit()
  if (!initialized) {
    await navigateTo('/init')
  }
  
  // 检查是否已经登录
  authStore.initFromStorage()
  if (authStore.isAuthenticated) {
    await navigateTo('/')
  }
})

const handleLogin = async () => {
  error.value = ''
  
  const result = await authStore.login(form)
  
  if (result.success) {
    await navigateTo('/')
  } else {
    error.value = result.message
  }
}
</script>
