// ui/src/components/servers/GameIniEditor.tsx
"use client";

import { useState, useEffect, useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Info, RotateCcw, Eye, EyeOff } from 'lucide-react';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

// Game.ini configuration parameters
interface GameIniParam {
  type: 'boolean' | 'number' | 'text';
  default: boolean | number | string;
  min?: number;
  max?: number;
  step?: number;
}

type GameIniCategoryKey =
  | 'gameBasic'
  | 'experienceSettings'
  | 'breedingSettings'
  | 'itemSettings'
  | 'dinoSettings'
  | 'tribeSettings'
  | 'pvpSettings'
  | 'structureSettings'
  | 'advancedSettings'
  | 'customSettings';

const gameIniParams: Record<GameIniCategoryKey, Record<string, GameIniParam>> = {
  gameBasic: {
    bUseSingleplayerSettings: { type: 'boolean', default: false },
    bDisableStructurePlacementCollision: { type: 'boolean', default: false },
    bAllowFlyerCarryPvE: { type: 'boolean', default: true },
    bDisableStructureDecayPvE: { type: 'boolean', default: false },
    bAllowUnlimitedRespecs: { type: 'boolean', default: true },
    bAllowPlatformSaddleMultiFloors: { type: 'boolean', default: true },
    bPassiveDefensesDamageRiderlessDinos: { type: 'boolean', default: true },
    bPvEDisableFriendlyFire: { type: 'boolean', default: false },
    bDisableFriendlyFire: { type: 'boolean', default: false },
    bEnablePvPGamma: { type: 'boolean', default: false },
    DifficultyOffset: { type: 'number', default: 1.0, min: 0.0, max: 1.0, step: 0.1 },
    OverrideOfficialDifficulty: { type: 'number', default: 5.0, min: 1.0, max: 10.0, step: 0.1 }
  },
  experienceSettings: {
    XPMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    PlayerCharacterWaterDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    PlayerCharacterFoodDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    PlayerCharacterStaminaDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    PlayerCharacterHealthRecoveryMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 }
  },
  breedingSettings: {
    MatingIntervalMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    EggHatchSpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 50.0, step: 0.1 },
    BabyMatureSpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 50.0, step: 0.1 },
    BabyFoodConsumptionSpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    BabyCuddleIntervalMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    BabyCuddleGracePeriodMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    BabyCuddleLoseImprintQualitySpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 }
  },
  itemSettings: {
    HarvestAmountMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    HarvestHealthMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    ResourcesRespawnPeriodMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    ItemStackSizeMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    CropGrowthSpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    GlobalItemDecompositionTimeMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    GlobalCorpseDecompositionTimeMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 }
  },
  dinoSettings: {
    TamingSpeedMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 50.0, step: 0.1 },
    DinoCharacterFoodDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    DinoCharacterStaminaDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    DinoCharacterHealthRecoveryMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    DinoCountMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    WildDinoCharacterFoodDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    WildDinoTorporDrainMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 }
  },
  tribeSettings: {
    MaxNumberOfPlayersInTribe: { type: 'number', default: 0, min: 0, max: 100, step: 1 },
    TribeNameChangeCooldown: { type: 'number', default: 15, min: 0, max: 1440, step: 1 },
    bPvEAllowTribeWar: { type: 'boolean', default: false },
    bPvEAllowTribeWarCancel: { type: 'boolean', default: false }
  },
  pvpSettings: {
    bIncreasePvPRespawnInterval: { type: 'boolean', default: false },
    IncreasePvPRespawnIntervalCheckPeriod: { type: 'number', default: 300, min: 60, max: 3600, step: 60 },
    IncreasePvPRespawnIntervalMultiplier: { type: 'number', default: 1.0, min: 1.0, max: 5.0, step: 0.1 },
    IncreasePvPRespawnIntervalBaseAmount: { type: 'number', default: 60, min: 30, max: 600, step: 30 }
  },
  structureSettings: {
    StructureDamageMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    StructureResistanceMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    StructureDamageRepairCooldown: { type: 'number', default: 180, min: 0, max: 3600, step: 60 },
    PvEStructureDecayPeriodMultiplier: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    MaxStructuresInRange: { type: 'number', default: 1300, min: 100, max: 10000, step: 100 }
  },
  advancedSettings: {
    bAutoPvETimer: { type: 'boolean', default: false },
    bAutoPvEUseSystemTime: { type: 'boolean', default: false },
    AutoPvEStartTimeSeconds: { type: 'number', default: 0, min: 0, max: 86400, step: 3600 },
    AutoPvEStopTimeSeconds: { type: 'number', default: 0, min: 0, max: 86400, step: 3600 },
    bOnlyAllowSpecifiedEngrams: { type: 'boolean', default: false },
    bAutoUnlockAllEngrams: { type: 'boolean', default: false },
    bShowCreativeMode: { type: 'boolean', default: false },
    bUseCorpseLocator: { type: 'boolean', default: false },
    bDisableLootCrates: { type: 'boolean', default: false },
    bDisableDinoRiding: { type: 'boolean', default: false },
    bDisableDinoTaming: { type: 'boolean', default: false },
    bAllowCustomRecipes: { type: 'boolean', default: true }
  },
  customSettings: {
    DayCycleSpeedScale: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    NightTimeSpeedScale: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 },
    DayTimeSpeedScale: { type: 'number', default: 1.0, min: 0.1, max: 10.0, step: 0.1 }
  }
};

function getGameIniParamsByCategory(category: GameIniCategoryKey): Record<string, GameIniParam> {
  return gameIniParams[category] || {};
}



interface GameIniEditorProps {
  value?: string;
  onChange?: (value: string) => void;
}

export function GameIniEditor({ value, onChange }: GameIniEditorProps) {
  const t = useTranslations('servers.editor');
  const tCategories = useTranslations('servers.gameIniCategories');
  const tParams = useTranslations('servers.gameIniParams');
  const [editMode, setEditMode] = useState<'visual' | 'text'>('visual');
  const [isSyncing, setIsSyncing] = useState(false);
  const [textContent, setTextContent] = useState('');
  const [visualConfig, setVisualConfig] = useState<Record<string, string | number | boolean>>({});
  const [activeTab, setActiveTab] = useState<GameIniCategoryKey>('gameBasic');
  const [showTooltip, setShowTooltip] = useState<string | null>(null);
  const [isUserEditing, setIsUserEditing] = useState(false);
  const [lastUserEditTime, setLastUserEditTime] = useState(0);

  // Get parameter display name from translations
  const getParamDisplayName = (paramKey: string): string => {
    try {
      return tParams(paramKey);
    } catch {
      return paramKey; // Fallback to parameter key if translation not found
    }
  };

  // Initialize with default values
  useEffect(() => {
    if (!value) {
      const defaultConfig: Record<string, string | number | boolean> = {};
      Object.keys(gameIniParams).forEach(categoryKey => {
        const category = categoryKey as GameIniCategoryKey;
        const params = getGameIniParamsByCategory(category);
        Object.keys(params).forEach(paramKey => {
          defaultConfig[paramKey] = params[paramKey].default;
        });
      });
      setVisualConfig(defaultConfig);
    } else {
      setTextContent(value);
      parseTextToVisual(value);
    }
  }, [value]);

  const parseTextToVisual = useCallback((text: string) => {
    try {
      const config: Record<string, string | number | boolean> = {};
      const lines = text.split('\n');

      for (const line of lines) {
        const trimmedLine = line.trim();
        if (trimmedLine && !trimmedLine.startsWith(';') && !trimmedLine.startsWith('#') && !trimmedLine.startsWith('[')) {
          const [key, ...valueParts] = trimmedLine.split('=');
          if (key && valueParts.length > 0) {
            const value = valueParts.join('=').trim();

            // Find parameter definition
            let paramDef: GameIniParam | undefined;
            for (const categoryKey of Object.keys(gameIniParams)) {
              const category = categoryKey as GameIniCategoryKey;
              const params = getGameIniParamsByCategory(category);
              if (params[key.trim()]) {
                paramDef = params[key.trim()];
                break;
              }
            }

            if (paramDef) {
              if (paramDef.type === 'boolean') {
                config[key.trim()] = value.toLowerCase() === 'true';
              } else if (paramDef.type === 'number') {
                const numValue = parseFloat(value);
                config[key.trim()] = isNaN(numValue) ? paramDef.default : numValue;
              } else {
                config[key.trim()] = value;
              }
            }
          }
        }
      }

      setVisualConfig(config);
    } catch (error) {
      console.error(t('parseGameIniError') + ':', error);
    }
  }, []);

  const syncVisualToText = useCallback(() => {
    try {
      let iniContent = '';

      // Add sections based on categories
      iniContent += '[/script/shootergame.shootergamemode]\n';

      // Basic game settings
      const gameBasicParams = getGameIniParamsByCategory('gameBasic');
      Object.keys(gameBasicParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Tribe settings
      const tribeParams = getGameIniParamsByCategory('tribeSettings');
      Object.keys(tribeParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      iniContent += '\n[/Script/ShooterGame.ShooterGameMode]\n';

      // Experience settings
      const expParams = getGameIniParamsByCategory('experienceSettings');
      Object.keys(expParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Item settings
      const itemParams = getGameIniParamsByCategory('itemSettings');
      Object.keys(itemParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Dino settings
      const dinoParams = getGameIniParamsByCategory('dinoSettings');
      Object.keys(dinoParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Breeding settings
      const breedingParams = getGameIniParamsByCategory('breedingSettings');
      Object.keys(breedingParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // PvP settings
      const pvpParams = getGameIniParamsByCategory('pvpSettings');
      Object.keys(pvpParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Structure settings
      const structureParams = getGameIniParamsByCategory('structureSettings');
      Object.keys(structureParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Advanced settings
      const advancedParams = getGameIniParamsByCategory('advancedSettings');
      Object.keys(advancedParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      // Custom settings
      const customParams = getGameIniParamsByCategory('customSettings');
      Object.keys(customParams).forEach(key => {
        const value = visualConfig[key];
        if (value !== undefined) {
          iniContent += `${key}=${value}\n`;
        }
      });

      setTextContent(iniContent);
      onChange?.(iniContent);
    } catch (error) {
      console.error(t('syncVisualToTextError') + ':', error);
    }
  }, [visualConfig, onChange]);

  // Sync visual to text when visual config changes
  useEffect(() => {
    if (editMode === 'visual' && !isUserEditing) {
      const now = Date.now();
      if (now - lastUserEditTime > 500) {
        syncVisualToText();
      }
    }
  }, [visualConfig, editMode, syncVisualToText, isUserEditing, lastUserEditTime]);

  const handleVisualChange = (key: string, value: string | number | boolean) => {
    setIsUserEditing(true);
    setLastUserEditTime(Date.now());
    setVisualConfig(prev => ({ ...prev, [key]: value }));
    setTimeout(() => setIsUserEditing(false), 1000);
  };

  const handleTextChange = (newText: string) => {
    setTextContent(newText);
    onChange?.(newText);

    // Parse text to visual with debounce
    setTimeout(() => {
      parseTextToVisual(newText);
    }, 500);
  };

  const handleModeSwitch = (mode: 'visual' | 'text') => {
    if (mode === 'text' && editMode === 'visual') {
      syncVisualToText();
    } else if (mode === 'visual' && editMode === 'text') {
      parseTextToVisual(textContent);
    }
    setEditMode(mode);
  };

  const resetToDefault = () => {
    const defaultConfig: Record<string, string | number | boolean> = {};
    Object.keys(gameIniParams).forEach(categoryKey => {
      const category = categoryKey as GameIniCategoryKey;
      const params = getGameIniParamsByCategory(category);
      Object.keys(params).forEach(paramKey => {
        defaultConfig[paramKey] = params[paramKey].default;
      });
    });
    setVisualConfig(defaultConfig);
  };

  const getCategoryDisplayName = (categoryKey: GameIniCategoryKey): string => {
    const translated = tCategories(categoryKey as any);
    return translated !== categoryKey ? translated : categoryKey;
  };

  const renderParamControl = (paramKey: string, param: GameIniParam) => {
    const currentValue = visualConfig[paramKey] ?? param.default;

    switch (param.type) {
      case 'boolean':
        return (
          <div className="flex items-center space-x-2">
            <Switch
              checked={Boolean(currentValue)}
              onCheckedChange={(checked) => handleVisualChange(paramKey, checked)}
            />
            <span className="text-sm text-muted-foreground">
              {Boolean(currentValue) ? t('enabled') : t('disabled')}
            </span>
          </div>
        );

      case 'number':
        return (
          <div className="space-y-1">
            <Input
              type="number"
              value={String(currentValue)}
              onChange={(e) => {
                const value = parseFloat(e.target.value);
                if (!isNaN(value)) {
                  handleVisualChange(paramKey, value);
                }
              }}
              min={param.min}
              max={param.max}
              step={param.step}
              className="w-full"
            />
            {(param.min !== undefined || param.max !== undefined) && (
              <div className="text-xs text-muted-foreground">
                {t('range')}: {param.min ?? '∞'} - {param.max ?? '∞'}
              </div>
            )}
          </div>
        );

      case 'text':
        return (
          <Input
            type="text"
            value={String(currentValue)}
            onChange={(e) => handleVisualChange(paramKey, e.target.value)}
            className="w-full"
          />
        );

      default:
        return null;
    }
  };

  return (
    <div className="space-y-4">
      {/* Mode Switch */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <Button
            variant={editMode === 'visual' ? 'default' : 'outline'}
            size="sm"
            onClick={() => handleModeSwitch('visual')}
          >
            <Eye className="w-4 h-4 mr-1" />
            {t('visualEditMode')}
          </Button>
          <Button
            variant={editMode === 'text' ? 'default' : 'outline'}
            size="sm"
            onClick={() => handleModeSwitch('text')}
          >
            <EyeOff className="w-4 h-4 mr-1" />
            {t('textEditMode')}
          </Button>
        </div>

        {editMode === 'visual' && (
          <Button variant="outline" size="sm" onClick={resetToDefault}>
            <RotateCcw className="w-4 h-4 mr-1" />
            {t('resetToDefault')}
          </Button>
        )}
      </div>

      {/* Mode Description */}
      <div className="text-sm text-muted-foreground p-3 bg-muted/50 rounded-md">
        {editMode === 'visual' ? t('visualEditModeTip') : t('gameIniTextEditDesc')}
      </div>

      {editMode === 'visual' ? (
        <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as GameIniCategoryKey)}>
          <TabsList className="grid w-full grid-cols-5 lg:grid-cols-10">
            {Object.keys(gameIniParams).map((categoryKey) => (
              <TabsTrigger key={categoryKey} value={categoryKey} className="text-xs">
                {getCategoryDisplayName(categoryKey as GameIniCategoryKey)}
              </TabsTrigger>
            ))}
          </TabsList>

          {Object.keys(gameIniParams).map((categoryKey) => {
            const category = categoryKey as GameIniCategoryKey;
            const params = getGameIniParamsByCategory(category);

            return (
              <TabsContent key={categoryKey} value={categoryKey} className="space-y-4">
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">
                      {getCategoryDisplayName(category)}
                    </CardTitle>
                    <CardDescription>
                      {Object.keys(params).length}{t('parametersCount')}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid gap-4">
                      {Object.keys(params).map((paramKey) => {
                        const param = params[paramKey];
                        return (
                          <div key={paramKey} className="space-y-2">
                            <Label className="text-sm font-medium">
                              {getParamDisplayName(paramKey)}
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <Info className="w-4 h-4 ml-1 inline-block cursor-help" />
                                  </TooltipTrigger>
                                  <TooltipContent>
                                    <div className="max-w-xs">
                                      <p className="font-medium">{paramKey}</p>
                                      <p className="text-sm mt-1">{getParamDisplayName(paramKey)}</p>
                                      <p className="text-xs mt-1 text-muted-foreground">
                                        {t('defaultValue')}: {String(param.default)}
                                      </p>
                                    </div>
                                  </TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                            </Label>
                            {renderParamControl(paramKey, param)}
                          </div>
                        );
                      })}
                    </div>
                  </CardContent>
                </Card>
              </TabsContent>
            );
          })}
        </Tabs>
      ) : (
        <div className="space-y-2">
          <Label htmlFor="game-ini-text">{t('textEditMode')}</Label>
          <Textarea
            id="game-ini-text"
            value={textContent}
            onChange={(e) => handleTextChange(e.target.value)}
            className="min-h-[400px] font-mono text-sm"
            placeholder={t('placeholders.gameIni')}
          />
        </div>
      )}
    </div>
  );
}

// ui/app/components/servers/GameIniEditor.vue
<template>
  <div class="space-y-4">
    <!-- 编辑模式切换 -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div class="flex flex-wrap gap-2 sm:gap-4">
        <button
          @click="switchToVisualMode"
          :class="[
            'px-3 py-2 rounded-md text-sm font-medium transition-colors',
            editMode === 'visual'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
          ]"
        >
          <i class="fas fa-sliders-h mr-2"></i>{{ t('servers.editor.visualEdit') }}
        </button>
        <button
          @click="switchToTextMode"
          :class="[
            'px-3 py-2 rounded-md text-sm font-medium transition-colors',
            editMode === 'text'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
          ]"
        >
          <i class="fas fa-code mr-2"></i>{{ t('servers.editor.textEdit') }}
        </button>
      </div>
      <div class="flex flex-col sm:flex-row items-start sm:items-center gap-2 sm:gap-4">
        <div class="text-sm text-gray-500">
          Game.ini - {{ editMode === 'visual' ? t('servers.editor.visualEditMode') : t('servers.editor.textEditMode') }}
        </div>
        <div v-if="isSyncing" class="flex items-center text-sm text-blue-600">
          <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600 mr-2"></div>
          {{ t('servers.editor.syncing') }}
        </div>
        <div v-else class="flex items-center text-sm text-green-600">
          <i class="fas fa-check-circle mr-1"></i>
          {{ t('servers.editor.synced') }}
        </div>
      </div>
    </div>

    <!-- 可视化编辑模式 -->
    <div v-if="editMode === 'visual'" class="space-y-6">
      <!-- 页签导航 -->
      <div class="border-b border-gray-200">
        <nav class="-mb-px flex space-x-8 overflow-x-auto">
          <button
            v-for="category in getAllGameIniCategories()"
            :key="category.key"
            @click="activeTab = category.key"
            :class="[
              'whitespace-nowrap py-2 px-1 border-b-2 font-medium text-sm',
              activeTab === category.key
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            ]"
          >
            {{ getCategoryName(category.key) }}
          </button>
        </nav>
      </div>

      <!-- 页签内容 -->
      <div class="bg-white rounded-lg border border-gray-200 p-6">
        <div
          v-for="category in getAllGameIniCategories()"
          :key="category.key"
          v-show="activeTab === category.key"
          class="space-y-4"
        >
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            <div 
              v-for="{ key: paramKey, param } in category.params" 
              :key="paramKey"
              class="space-y-2 relative"
            >
              <label class="block text-sm font-medium text-gray-700">
                {{ getParamDisplayName(paramKey) }}
                <span 
                  class="relative inline-block ml-1"
                  @mouseenter="showTooltip = paramKey"
                  @mouseleave="showTooltip = null"
                >
                  <i class="fas fa-info-circle text-gray-400 cursor-help"></i>
                  <div 
                    v-if="showTooltip === paramKey"
                    class="absolute z-30 bg-gray-900 text-white text-xs rounded py-2 px-3 max-w-xs whitespace-normal shadow-lg"
                    style="bottom: 100%; left: 50%; transform: translateX(-50%); margin-bottom: 8px;"
                  >
                    {{ getParamDisplayName(paramKey) }}
                    <div class="absolute top-full left-1/2 transform -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-transparent border-t-gray-900"></div>
                  </div>
                </span>
              </label>
              
              <!-- Boolean 类型 -->
              <div v-if="param.type === 'boolean'">
                <ToggleSwitch
                  :id="paramKey"
                  v-model="visualConfig[paramKey]"
                  :label="visualConfig[paramKey] ? t('servers.editor.enabled') : t('servers.editor.disabled')"
                />
              </div>
              
              <!-- Number 类型 -->
              <input
                v-else-if="param.type === 'number'"
                v-model.number="visualConfig[paramKey]"
                type="number"
                :min="param.min"
                :max="param.max"
                :step="param.step || 1"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              
              <!-- Text 类型 -->
              <input
                v-else
                v-model="visualConfig[paramKey]"
                type="text"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 文本编辑模式 -->
    <div v-else>
      <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-2 gap-2">
        <label class="block text-sm font-medium text-gray-700">
          Game.ini {{ t('servers.editor.content') }}
        </label>
        <div class="flex gap-2">
          <button
            @click="resetToDefault"
            class="text-sm text-blue-600 hover:text-blue-800"
          >
            {{ t('servers.editor.resetToDefault') }}
          </button>
          <button
            @click="formatConfig"
            class="text-sm text-green-600 hover:text-green-800"
          >
            {{ t('servers.editor.format') }}
          </button>
        </div>
      </div>
      <textarea
        v-model="textContent"
        class="w-full h-64 sm:h-96 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
        :placeholder="t('servers.editor.placeholder')"
      ></textarea>
      <p class="text-xs text-gray-500 mt-1">
        {{ t('servers.editor.description') }}
      </p>
    </div>

    <!-- 提示信息 -->
    <div v-if="editMode === 'visual'" class="bg-blue-50 border border-blue-200 rounded-lg p-4">
      <div class="flex flex-col sm:flex-row items-start">
        <i class="fas fa-info-circle text-blue-500 mr-0 sm:mr-3 mb-2 sm:mb-0"></i>
        <div class="text-sm text-blue-700">
          <p class="font-medium">{{ t('servers.editor.visualEditModeDesc') }}</p>
          <p>{{ t('servers.editor.visualEditModeTip') }}</p>
        </div>
      </div>
    </div>

    <div v-if="editMode === 'text'" class="bg-green-50 border border-green-200 rounded-lg p-4">
      <div class="flex flex-col sm:flex-row items-start">
        <i class="fas fa-code text-green-500 mr-0 sm:mr-3 mb-2 sm:mb-0"></i>
        <div class="text-sm text-green-700">
          <p class="font-medium">{{ t('servers.editor.textEditMode') }}</p>
          <p>{{ t('servers.editor.gameIniTextEditDesc') }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { gameIniParams, getAllGameIniCategories } from '../../utils/gameIniParams'
import { extractConfigValues, formatConfigContent, mergeConfigContent } from '../../utils/configParser'
import ToggleSwitch from '../ToggleSwitch.vue'

// i18n
const { t } = useI18n()

// Props
const props = defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  server: {
    type: Object,
    default: null
  }
})

// Emits
const emit = defineEmits(['update:modelValue'])

// 响应式状态
const editMode = ref('visual')
const showTooltip = ref(null)
const isSyncing = ref(false)
const textContent = ref('')
const visualConfig = ref({})
const isInitialized = ref(false)
const activeTab = ref('')

// 防抖定时器
let visualSyncTimer = null
let textSyncTimer = null

// i18n 相关函数
const getCategoryName = (categoryKey) => {
  const translated = t(`servers.gameIniCategories.${categoryKey}`)
  return translated !== `servers.gameIniCategories.${categoryKey}` ? translated : categoryKey
}

const getParamDisplayName = (paramKey) => {
  const translated = t(`servers.gameIniParams.${paramKey}`)
  return translated !== `servers.gameIniParams.${paramKey}` ? translated : paramKey
}

// 初始化可视化配置默认值
const initializeVisualConfig = () => {
  try {
    if (!gameIniParams) {
      console.warn('Game.ini 配置参数尚未加载，跳过初始化')
      return
    }

    // 只在未初始化时设置默认值
    if (!isInitialized.value) {
      Object.keys(gameIniParams).forEach(sectionKey => {
        const section = gameIniParams[sectionKey]
        if (section) {
          Object.keys(section).forEach(paramKey => {
            const param = section[paramKey]
            if (param && param.default !== undefined) {
              visualConfig.value[paramKey] = param.default
            }
          })
        }
      })
      isInitialized.value = true
      console.log('Game.ini 可视化配置初始化完成')
    }
  } catch (error) {
    console.error('初始化 Game.ini 可视化配置失败:', error)
  }
}

// 解析文本配置到可视化配置
const parseTextToVisual = () => {
  try {
    if (!gameIniParams) {
      console.warn('Game.ini 配置参数尚未加载')
      return
    }

    if (textContent.value) {
      console.log('开始解析 Game.ini 配置文件到可视化配置')
      const values = extractConfigValues(
        textContent.value, 
        gameIniParams
      )
      if (values && Object.keys(values).length > 0) {
        // 合并解析的值，保留未解析参数的默认值
        Object.keys(values).forEach(key => {
          if (values[key] !== undefined && values[key] !== null) {
            visualConfig.value[key] = values[key]
          }
        })
        console.log('Game.ini 配置文件解析完成，更新了', Object.keys(values).length, '个参数')
      }
    }
  } catch (error) {
    console.error('解析 Game.ini 配置文件失败:', error)
  }
}

// 将可视化配置同步到文本
const syncVisualToText = () => {
  try {
    if (!gameIniParams) {
      console.warn('Game.ini 配置参数尚未加载，无法同步')
      return
    }

    // 使用智能合并，保留用户自定义的配置
    const mergedContent = mergeConfigContent(
      textContent.value,
      visualConfig.value,
      gameIniParams,
      ['/script/shootergame.shootergamemode', '/script/engine.gamesession']
    )

    textContent.value = mergedContent
    emit('update:modelValue', mergedContent)
  } catch (error) {
    console.error('同步 Game.ini 可视化配置到文本失败:', error)
  }
}

// 监听 props.modelValue 变化
watch(() => props.modelValue, (newValue) => {
  if (newValue !== textContent.value) {
    textContent.value = newValue || ''
    // 只有在 gameIniParams 已加载且处于可视化模式时才解析
    if (gameIniParams && editMode.value === 'visual') {
      parseTextToVisual()
    }
  }
}, { immediate: true })

// 监听 gameIniParams 的变化（处理异步加载）
watch(() => gameIniParams, (newParams) => {
  if (newParams) {
    console.log('Game.ini 参数已加载，重新初始化')
    initializeVisualConfig()
    // 如果已经有文本内容且处于可视化模式，解析配置
    if (textContent.value && editMode.value === 'visual') {
      parseTextToVisual()
    }
  }
}, { immediate: true })

// 监听可视化配置变化，自动同步到文本
watch(() => visualConfig.value, () => {
  if (editMode.value === 'visual' && isInitialized.value) {
    isSyncing.value = true
    if (visualSyncTimer) {
      clearTimeout(visualSyncTimer)
    }
    visualSyncTimer = setTimeout(() => {
      syncVisualToText()
      isSyncing.value = false
    }, 500)
  }
}, { deep: true })

// 监听文本配置变化，自动同步到可视化
watch(() => textContent.value, () => {
  if (editMode.value === 'text') {
    isSyncing.value = true
    if (textSyncTimer) {
      clearTimeout(textSyncTimer)
    }
    textSyncTimer = setTimeout(() => {
      parseTextToVisual()
      emit('update:modelValue', textContent.value)
      isSyncing.value = false
    }, 800)
  }
})

// 切换到可视化模式
const switchToVisualMode = () => {
  if (editMode.value !== 'visual') {
    editMode.value = 'visual'
    // 确保在切换时解析文本配置
    if (textContent.value && gameIniParams) {
      parseTextToVisual()
    }
  }
}

// 切换到文本模式
const switchToTextMode = () => {
  if (editMode.value !== 'text') {
    editMode.value = 'text'
    syncVisualToText()
  }
}

// 重置为默认配置
const resetToDefault = () => {
  if (!props.server) return
  
  const server = props.server
  
  textContent.value = `[/script/shootergame.shootergamemode]
# 基础游戏设置
bUseSingleplayerSettings=false
bDisableStructurePlacementCollision=false
bAllowFlyerCarryPvE=true
bAllowUnlimitedRespecs=true
bPassiveDefensesDamageRiderlessDinos=true
bAllowCustomRecipes=true
bUseCorpseLocator=false
bDisableLootCrates=false
bPvEDisableFriendlyFire=false
bDisableFriendlyFire=false

# 经验值和等级设置
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0
OverridePlayerLevelEngramPoints=0
KillXPMultiplier=1.0
HarvestXPMultiplier=1.0
CraftXPMultiplier=1.0
GenericXPMultiplier=1.0
SpecialXPMultiplier=1.0

# 繁殖设置
MatingIntervalMultiplier=1.0
MatingSpeedMultiplier=1.0
EggHatchSpeedMultiplier=1.0
BabyMatureSpeedMultiplier=1.0
BabyCuddleIntervalMultiplier=1.0
BabyFoodConsumptionSpeedMultiplier=1.0
BabyImprintingStatScaleMultiplier=1.0
BabyImprintAmountMultiplier=1.0
BabyCuddleGracePeriodMultiplier=1.0
BabyCuddleLoseImprintQualitySpeedMultiplier=1.0

# 物品和资源设置
CropGrowthSpeedMultiplier=1.0
CropDecaySpeedMultiplier=1.0
GlobalSpoilingTimeMultiplier=1.0
GlobalItemDecompositionTimeMultiplier=1.0
GlobalCorpseDecompositionTimeMultiplier=1.0
UseCorpseLifeSpanMultiplier=1.0
SupplyCrateLootQualityMultiplier=1.0
FishingLootQualityMultiplier=1.0
CustomRecipeEffectivenessMultiplier=1.0
CustomRecipeSkillMultiplier=1.0
CraftingSkillBonusMultiplier=1.0
ResourceNoReplenishRadiusPlayers=1.0
ResourceNoReplenishRadiusStructures=1.0
DinoHarvestingDamageMultiplier=1.0
PlayerHarvestingDamageMultiplier=1.0

# 恐龙设置
TamedDinoCharacterFoodDrainMultiplier=1.0
WildDinoCharacterFoodDrainMultiplier=1.0
WildDinoTorporDrainMultiplier=1.0
TamedDinoTorporDrainMultiplier=1.0
PassiveTameIntervalMultiplier=1.0
DinoTurretDamageMultiplier=1.0
DestroyTamesOverLevelClamp=0

# 部落和玩家设置
MaxNumberOfPlayersInTribe=0
MaxAlliancesPerTribe=0
MaxTribesPerAlliance=0
TribeSlotReuseCooldown=0
MaxTribeLogs=100
KickIdlePlayersPeriod=0

# PvP设置
IncreasePvPRespawnIntervalCheckPeriod=300
IncreasePvPRespawnIntervalMultiplier=2.0
IncreasePvPRespawnIntervalBaseAmount=60
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
PvPZoneStructureDamageMultiplier=1.0

# 建筑和结构设置
StructureDamageRepairCooldown=180
StructureResistanceMultiplier=1.0
StructureDamageMultiplier=1.0
PvEStructureDecayPeriodMultiplier=1.0
FastDecayInterval=0

# 高级设置
HairGrowthSpeedMultiplier=1.0
PoopIntervalMultiplier=1.0
LayEggIntervalMultiplier=1.0
FuelConsumptionIntervalMultiplier=1.0
GlobalPoweredBatteryDurabilityDecreasePerSecond=0
LimitNonPlayerDroppedItemsRange=0
LimitNonPlayerDroppedItemsCount=0
MaxFallSpeedMultiplier=1.0
PreventOfflinePvPConnectionInvincibleInterval=0

[/script/engine.gamesession]
MaxPlayers=70

[/Script/ShooterGame.ShooterGameMode]
DifficultyOffset=1.0
OverrideOfficialDifficulty=5.0

# 资源重生倍率
ResourcesRespawnPeriodMultiplier=1.0

# 驯服相关设置
TamingSpeedMultiplier=1.0
DinoCharacterFoodDrainMultiplier=1.0
DinoCharacterStaminaDrainMultiplier=1.0
DinoCharacterHealthRecoveryMultiplier=1.0
DinoCountMultiplier=1.0

# 经验值倍率
XPMultiplier=1.0
PlayerCharacterWaterDrainMultiplier=1.0
PlayerCharacterFoodDrainMultiplier=1.0
PlayerCharacterStaminaDrainMultiplier=1.0
PlayerCharacterHealthRecoveryMultiplier=1.0

# 收集倍率
HarvestAmountMultiplier=1.0
HarvestHealthMultiplier=1.0

# 白天/夜晚时间流逝速度
DayCycleSpeedScale=1.0
NightTimeSpeedScale=1.0

# PvP相关设置
bEnablePvPGamma=false`

  emit('update:modelValue', textContent.value)
}

// 格式化配置文件内容
const formatConfig = () => {
  textContent.value = formatConfigContent(textContent.value)
  emit('update:modelValue', textContent.value)
}

// 组件挂载时初始化
onMounted(() => {
  initializeVisualConfig()
  
  // 初始化第一个页签
  const categories = getAllGameIniCategories()
  if (categories.length > 0 && !activeTab.value) {
    activeTab.value = categories[0].key
  }
})

// 组件卸载时清理定时器
onUnmounted(() => {
  if (visualSyncTimer) {
    clearTimeout(visualSyncTimer)
  }
  if (textSyncTimer) {
    clearTimeout(textSyncTimer)
  }
})
</script>
