// ui/app/pages/init.vue
<template>
  <div class="min-h-screen flex flex-col bg-gradient-to-br from-green-50 to-emerald-100">
    <div class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="w-full max-w-md">
        <!-- Logo 和标题区域 -->
        <div class="text-center mb-8">
          <div class="mx-auto w-16 h-16 bg-green-600 rounded-full flex items-center justify-center mb-4">
            <UIcon name="i-lucide-settings" class="w-8 h-8 text-white" />
          </div>
          <h1 class="text-3xl font-bold text-gray-900 mb-2">
            {{ $t('auth.initTitle') }}
          </h1>
          <p class="text-gray-600">
            {{ $t('auth.initSubtitle') }}
          </p>
        </div>
        
        <!-- 初始化表单卡片 -->
        <UCard class="shadow-xl">
          <form @submit.prevent="handleInit" class="space-y-6">
            <!-- 错误提示 -->
            <UAlert
              v-if="error"
              :title="error"
              color="red"
              variant="soft"
              icon="i-lucide-alert-circle"
            />
            
            <!-- 成功提示 -->
            <UAlert
              v-if="success"
              :title="success"
              color="green"
              variant="soft"
              icon="i-lucide-check-circle"
            />
            
            <!-- 用户名输入 -->
            <UFormGroup :label="$t('auth.adminUsername')" name="username">
              <UInput
                v-model="form.username"
                :placeholder="$t('auth.enterAdminUsername')"
                icon="i-lucide-user"
                size="lg"
                required
              />
            </UFormGroup>
            
            <!-- 密码输入 -->
            <UFormGroup :label="$t('auth.password')" name="password">
              <UInput
                v-model="form.password"
                type="password"
                placeholder="请输入密码 (至少6位)"
                icon="i-lucide-lock"
                size="lg"
                required
                minlength="6"
              />
              <template #help>
                <p class="text-xs text-gray-500 mt-1">
                  {{ $t('auth.passwordMinLength') }}
                </p>
              </template>
            </UFormGroup>
            
            <!-- 确认密码输入 -->
            <UFormGroup :label="$t('auth.confirmPassword')" name="confirmPassword">
              <UInput
                v-model="form.confirmPassword"
                type="password"
                :placeholder="$t('auth.enterConfirmPassword')"
                icon="i-lucide-lock"
                size="lg"
                required
              />
            </UFormGroup>

            <!-- 初始化按钮 -->
            <UButton
              type="submit"
              :loading="authStore.isLoading"
              :disabled="authStore.isLoading"
              color="green"
              variant="solid"
              size="lg"
              block
              class="mt-8"
            >
              <UIcon 
                v-if="!authStore.isLoading" 
                name="i-lucide-settings" 
                class="w-4 h-4 mr-2" 
              />
              {{ authStore.isLoading ? $t('auth.initLoading') : $t('auth.initButton') }}
            </UButton>
          </form>
        </UCard>
        
        <!-- 底部提示 -->
        <div class="text-center mt-6">
          <div class="flex items-center justify-center space-x-2 text-sm text-gray-500">
            <UIcon name="i-lucide-info" class="w-4 h-4" />
            <span>{{ $t('auth.initTip') }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- 初始化页面底部商标信息 -->
    <AppFooter 
      :show-privacy-policy="false"
      :show-terms-of-service="false"
      :page-info="$t('auth.initWizard')"
    />
  </div>
</template>

<script setup>
import { useAuthStore } from '~/stores/auth'

definePageMeta({
  layout: false
})

const authStore = useAuthStore()

const form = reactive({
  username: '',
  password: '',
  confirmPassword: ''
})

const error = ref('')
const success = ref('')

onMounted(async () => {
  // 检查是否已初始化
  const initialized = await authStore.checkInit()
  if (initialized) {
    await navigateTo('/login')
  }
})

const handleInit = async () => {
  error.value = ''
  success.value = ''
  
  // 验证密码
  if (form.password !== form.confirmPassword) {
    error.value = $t('auth.passwordMismatch')
    return
  }
  
  if (form.password.length < 6) {
    error.value = $t('auth.passwordMinLengthError')
    return
  }
  
  const result = await authStore.init({
    username: form.username,
    password: form.password
  })
  
  if (result.success) {
    success.value = result.message
    setTimeout(() => {
      navigateTo('/')
    }, 1500)
  } else {
    error.value = result.message
  }
}
</script>

// ui/src/app/[locale]/(auth)/init/page.tsx
"use client";

import { useEffect, useState } from 'react';
import { useAuthActions, useAuthIsLoading } from '@/stores/auth';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ClosableAlert } from "@/components/ui/closable-alert";
import { Settings, User, Lock, Info } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useRouter } from '@/navigation';

export default function InitPage() {
  const router = useRouter();
  const t = useTranslations('auth');
  const { init, checkInit } = useAuthActions();
  const isLoading = useAuthIsLoading();

  const [form, setForm] = useState({ username: '', password: '', confirmPassword: '' });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  useEffect(() => {
    const initialize = async () => {
      const initialized = await checkInit();
      if (initialized) {
        router.push('/login');
      }
    };
    initialize();
  }, [checkInit, router]);

  const handleInit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    if (form.password !== form.confirmPassword) {
      setError(t('passwordMismatch'));
      return;
    }
    if (form.password.length < 6) {
      setError(t('passwordMinLengthError'));
      return;
    }

    const result = await init({ username: form.username, password: form.password });
    if (result.success) {
      setSuccess(result.message);
      setTimeout(() => router.push('/'), 1500);
    } else {
      setError(result.message);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-green-50 to-emerald-100">
      <div className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-md">
          <div className="text-center mb-8">
            <div className="mx-auto w-16 h-16 bg-green-600 rounded-full flex items-center justify-center mb-4">
              <Settings className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              {t('initTitle')}
            </h1>
            <p className="text-gray-600">
              {t('initSubtitle')}
            </p>
          </div>

          <Card className="shadow-xl">
            <CardHeader>
              <CardTitle>{t('adminUsername')}</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleInit} className="space-y-6">
                {error && <ClosableAlert variant="destructive" title={t('loginError')} onClose={() => setError('')}>{error}</ClosableAlert>}
                {success && <ClosableAlert title={t('loginSuccess')} onClose={() => setSuccess('')}>{success}</ClosableAlert>}

                <div className="space-y-2">
                  <Label htmlFor="username">{t('adminUsername')}</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="username"
                      name="username"
                      value={form.username}
                      onChange={handleChange}
                      placeholder={t('enterAdminUsername')}
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">{t('password')}</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="password"
                      name="password"
                      type="password"
                      value={form.password}
                      onChange={handleChange}
                      placeholder={t('passwordMinLength')}
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">{t('confirmPassword')}</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <Input
                      id="confirmPassword"
                      name="confirmPassword"
                      type="password"
                      value={form.confirmPassword}
                      onChange={handleChange}
                      placeholder={t('enterConfirmPassword')}
                      required
                      className="pl-10"
                    />
                  </div>
                </div>
                <Button type="submit" disabled={isLoading} className="w-full mt-8" variant="default">
                  {isLoading ? t('initLoading') : t('initButton')}
                </Button>
              </form>
            </CardContent>
          </Card>

          <div className="text-center mt-6">
            <div className="flex items-center justify-center space-x-2 text-sm text-gray-500">
                <Info className="w-4 h-4" />
                <span>{t('initTip')}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
